public class BodyMassIndex {
    public static Decimal calBMI(Decimal x, Decimal y){
        decimal a = x / (y*y);
        System.debug(a);
        return a;
        //return x / (y*y);
        
    }
    
    public Static String BMIUpperCase(string firstName, string lastName){
        string fullName = firstName + ' '+ lastName;
        return fullName.toUpperCase();
        
    }
    
    

}